In [2]:
!pip install nba_api

Requirement already satisfied: nba_api in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (1.11.4)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from nba_api) (2.4.3)
Requirement already satisfied: pandas>=2.1.0 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from nba_api) (3.0.1)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from nba_api) (2.32.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from pandas>=2.1.0->nba_api) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from pandas>=2.1.0->nba_api) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2026.2.25)
Requirement already satisfied: six>=1.5 in c:\users\ryanl\documents\nba_2024\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.1.0->nba_api) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
from nba_api.stats.endpoints import leaguegamefinder

In [5]:
games = leaguegamefinder.LeagueGameFinder(
    season_nullable="2024-25"
)

df_2024_season_raw = games.get_data_frames()[0]

df_2024_season_raw.to_csv('nba_league_games_2024-25_raw.csv')

In [6]:
df_2024_season_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 2802 entries, 0 to 2801
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SEASON_ID          2802 non-null   str
 1   TEAM_ID            2802 non-null   int64
 2   TEAM_ABBREVIATION  2802 non-null   str
 3   TEAM_NAME          2802 non-null   str
 4   GAME_ID            2802 non-null   str
 5   GAME_DATE          2802 non-null   str
 6   MATCHUP            2802 non-null   str
 7   WL                 2802 non-null   str
 8   MIN                2802 non-null   int64
 9   PTS                2802 non-null   int64
 10  FGM                2802 non-null   int64
 11  FGA                2802 non-null   int64
 12  FG_PCT             2802 non-null   float64
 13  FG3M               2802 non-null   int64
 14  FG3A               2802 non-null   int64
 15  FG3_PCT            2802 non-null   float64
 16  FTM                2802 non-null   int64
 17  FTA                2802 non-null   int64
 18  FT_PCT             2796 non-null   float64
 19  OREB               2802 non-null   int64
 20  DREB               2802 non-null   int64
 21  REB                2802 non-null   int64
 22  AST                2802 non-null   int64
 23  STL                2802 non-null   int64
 24  BLK                2802 non-null   int64
 25  TOV                2802 non-null   int64
 26  PF                 2802 non-null   int64
 27  PLUS_MINUS         2802 non-null   float64
dtypes: float64(4), int64(17), str(7)
memory usage: 613.1 KB

In [7]:
df = df_2024_season_raw.copy()

# season_id

In [8]:
df['SEASON_ID'] = df['SEASON_ID'].astype(int)

In [9]:
df['SEASON_ID'].unique()

array([42024, 52024, 22024, 32024, 62024, 12024])

## 62024 NBA CUP

## 52024 Play-in Tournament

## 42024 playoff game

In [10]:
df_season_42024 = df[df['SEASON_ID']==42024]

In [11]:
df_season_42024

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42024,1610612754,IND,Indiana Pacers,0042400407,2025-06-22,IND @ OKC,L,240,91,...,0.759,12,33,45,17,6,4,21,24,-12.0
1,42024,1610612760,OKC,Oklahoma City Thunder,0042400407,2025-06-22,OKC vs. IND,W,240,103,...,0.710,13,27,40,20,14,8,7,23,12.0
2,42024,1610612754,IND,Indiana Pacers,0042400406,2025-06-19,IND vs. OKC,W,240,108,...,0.680,11,35,46,23,16,5,10,17,17.0
3,42024,1610612760,OKC,Oklahoma City Thunder,0042400406,2025-06-19,OKC @ IND,L,240,91,...,0.808,4,37,41,14,4,4,21,20,-17.0
4,42024,1610612760,OKC,Oklahoma City Thunder,0042400405,2025-06-16,OKC vs. IND,W,239,120,...,0.813,19,26,45,24,15,12,11,24,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,42024,1610612746,LAC,LA Clippers,0042400171,2025-04-19,LAC @ DEN,L,264,110,...,0.750,11,33,44,25,7,6,20,25,-2.0
164,42024,1610612750,MIN,Minnesota Timberwolves,0042400161,2025-04-19,MIN @ LAL,W,239,117,...,0.800,11,33,44,29,8,4,10,21,22.0
165,42024,1610612749,MIL,Milwaukee Bucks,0042400131,2025-04-19,MIL @ IND,L,241,98,...,0.679,8,33,41,15,4,3,10,20,-19.0
166,42024,1610612754,IND,Indiana Pacers,0042400131,2025-04-19,IND vs. MIL,W,239,117,...,0.769,5,38,43,28,6,6,5,22,19.0
167,42024,1610612747,LAL,Los Angeles Lakers,0042400161,2025-04-19,LAL vs. MIN,L,241,95,...,0.875,13,25,38,15,5,4,13,10,-22.0

In [12]:
df_season_52024 = df[df["SEASON_ID"]==52024]

In [13]:
df_season_52024.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
168,52024,1610612742,DAL,Dallas Mavericks,0052400211,2025-04-18,DAL @ MEM,L,239,106,...,0.750,7,29,36,25,9,8,16,17,-14.0
169,52024,1610612763,MEM,Memphis Grizzlies,0052400211,2025-04-18,MEM vs. DAL,W,241,120,...,0.867,16,34,50,30,8,4,10,17,14.0
170,52024,1610612748,MIA,Miami Heat,0052400201,2025-04-18,MIA @ ATL,W,266,123,...,0.611,13,41,54,33,4,8,14,15,9.0
171,52024,1610612737,ATL,Atlanta Hawks,0052400201,2025-04-18,ATL vs. MIA,L,265,114,...,0.833,11,33,44,30,12,3,9,18,-9.0
172,52024,1610612748,MIA,Miami Heat,0052400111,2025-04-16,MIA @ CHI,W,240,109,...,0.636,9,36,45,30,10,7,15,16,19.0

## 32024 All Star

## 22024 Regular Season

## 12024 Preseason

# team_id

# team_abbreviation

In [14]:
df['TEAM_ABBREVIATION'].unique()

<StringArray>
['IND', 'OKC', 'NYK', 'MIN', 'DEN', 'BOS', 'GSW', 'CLE', 'HOU', 'LAC', 'DET',
 'LAL', 'MIL', 'ORL', 'MIA', 'MEM', 'DAL', 'ATL', 'CHI', 'SAC', 'UTA', 'PHI',
 'WAS', 'PHX', 'CHA', 'NOP', 'BKN', 'TOR', 'SAS', 'POR', 'SHQ', 'CHK', 'CAN',
 'KEN', 'TMT', 'TMM', 'TMC', 'TMG', 'RCE', 'BND', 'ULM', 'NZB']
Length: 42, dtype: str

# team_name

In [15]:
df['TEAM_NAME'].unique()

<StringArray>
[        'Indiana Pacers',  'Oklahoma City Thunder',        'New York Knicks',
 'Minnesota Timberwolves',         'Denver Nuggets',         'Boston Celtics',
  'Golden State Warriors',    'Cleveland Cavaliers',        'Houston Rockets',
            'LA Clippers',        'Detroit Pistons',     'Los Angeles Lakers',
        'Milwaukee Bucks',          'Orlando Magic',             'Miami Heat',
      'Memphis Grizzlies',       'Dallas Mavericks',          'Atlanta Hawks',
          'Chicago Bulls',       'Sacramento Kings',              'Utah Jazz',
     'Philadelphia 76ers',     'Washington Wizards',           'Phoenix Suns',
      'Charlotte Hornets',   'New Orleans Pelicans',          'Brooklyn Nets',
        'Toronto Raptors',      'San Antonio Spurs', 'Portland Trail Blazers',
                   ' OGs',          ' Global Stars',          ' Rising Stars',
           ' Young Stars',                ' Team T',                ' Team M',
                ' Team C',         ' Team G League',              'Team Rice',
             'Team Bonds',         'Ratiopharm Ulm',   'New Zealand Breakers']
Length: 42, dtype: str

# GAME_ID

## needs to be int

In [16]:
df['GAME_ID'] = df['GAME_ID'].astype(int)

see if all games are duplicated once as we need an entry for each team playing a game

In [17]:
counts = df["GAME_ID"].value_counts()
counts.unique()

array([2])

# GAME_DATE

In [18]:
df['GAME_DATE'] = pd.to_datetime(df['GAME_DATE'], errors="raise")

# MATCHUP

either 'vs' or '@' in the middle indicating whether home and away team.

team with '@' means away team

team with 'vs' means home

In [19]:
df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42024,1610612754,IND,Indiana Pacers,42400407,2025-06-22,IND @ OKC,L,240,91,...,0.759,12,33,45,17,6,4,21,24,-12.0
1,42024,1610612760,OKC,Oklahoma City Thunder,42400407,2025-06-22,OKC vs. IND,W,240,103,...,0.710,13,27,40,20,14,8,7,23,12.0
2,42024,1610612754,IND,Indiana Pacers,42400406,2025-06-19,IND vs. OKC,W,240,108,...,0.680,11,35,46,23,16,5,10,17,17.0
3,42024,1610612760,OKC,Oklahoma City Thunder,42400406,2025-06-19,OKC @ IND,L,240,91,...,0.808,4,37,41,14,4,4,21,20,-17.0
4,42024,1610612760,OKC,Oklahoma City Thunder,42400405,2025-06-16,OKC vs. IND,W,239,120,...,0.813,19,26,45,24,15,12,11,24,11.0

## Add column HOME_TEAM which will be boolean

game at home will be marked with a true

In [20]:
def isHomeGame(val) -> bool:
    return "vs" in val

In [21]:
df["HOME_TEAM"] = df['MATCHUP'].apply(isHomeGame)

In [22]:
home_games = df.loc[df["HOME_TEAM"]]

In [23]:
home_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,HOME_TEAM
1,42024,1610612760,OKC,Oklahoma City Thunder,42400407,2025-06-22,OKC vs. IND,W,240,103,...,13,27,40,20,14,8,7,23,12.0,True
2,42024,1610612754,IND,Indiana Pacers,42400406,2025-06-19,IND vs. OKC,W,240,108,...,11,35,46,23,16,5,10,17,17.0,True
4,42024,1610612760,OKC,Oklahoma City Thunder,42400405,2025-06-16,OKC vs. IND,W,239,120,...,19,26,45,24,15,12,11,24,11.0,True
7,42024,1610612754,IND,Indiana Pacers,42400404,2025-06-13,IND vs. OKC,L,240,104,...,7,26,33,21,11,3,15,27,-7.0,True
8,42024,1610612754,IND,Indiana Pacers,42400403,2025-06-11,IND vs. OKC,W,239,116,...,7,29,36,24,13,11,13,24,9.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2789,12024,1610612747,LAL,Los Angeles Lakers,12400009,2024-10-06,LAL vs. PHX,L,238,114,...,7,42,49,31,9,7,17,18,-4.0,True
2792,12024,1610612766,CHA,Charlotte Hornets,12400006,2024-10-06,CHA vs. NYK,L,241,109,...,8,38,46,27,3,6,19,24,-2.0,True
2795,12024,1610612746,LAC,LA Clippers,12400004,2024-10-05,LAC vs. GSW,L,239,90,...,9,38,47,21,11,6,20,14,-1.0,True
2796,12024,1610612747,LAL,Los Angeles Lakers,12400003,2024-10-04,LAL vs. MIN,L,241,107,...,4,34,38,28,9,12,20,20,-17.0,True
2801,12024,1610612762,UTA,Utah Jazz,12400002,2024-10-04,UTA vs. NZB,W,238,116,...,9,35,44,27,11,5,21,19,29.0,True

# WL

In [24]:
df["WL"].unique()

<StringArray>
['L', 'W']
Length: 2, dtype: str

REST LOOKS GOOD

# 2024 df Transformation function

In [25]:
import pandas as pd

def isHomeGame(val) -> bool:
    return "vs" in val

def transform_games_df(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    df["GAME_ID"] = df["GAME_ID"].astype(int)
    df["GAME_DATE"] = pd.to_datetime(df["GAME_DATE"], errors="raise")
    df["HOME_TEAM"] = df["MATCHUP"].apply(isHomeGame)

    return df

In [26]:
df_final = df_2024_season_raw

In [27]:
df_final_standard = transform_games_df(df_final)

In [28]:
df_final_standard.info()

<class 'pandas.DataFrame'>
RangeIndex: 2802 entries, 0 to 2801
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SEASON_ID          2802 non-null   str
 1   TEAM_ID            2802 non-null   int64
 2   TEAM_ABBREVIATION  2802 non-null   str
 3   TEAM_NAME          2802 non-null   str
 4   GAME_ID            2802 non-null   int64
 5   GAME_DATE          2802 non-null   datetime64[us]
 6   MATCHUP            2802 non-null   str
 7   WL                 2802 non-null   str
 8   MIN                2802 non-null   int64
 9   PTS                2802 non-null   int64
 10  FGM                2802 non-null   int64
 11  FGA                2802 non-null   int64
 12  FG_PCT             2802 non-null   float64
 13  FG3M               2802 non-null   int64
 14  FG3A               2802 non-null   int64
 15  FG3_PCT            2802 non-null   float64
 16  FTM                2802 non-null   int64
 17  FTA                2802 non-null   int64
 18  FT_PCT             2796 non-null   float64
 19  OREB               2802 non-null   int64
 20  DREB               2802 non-null   int64
 21  REB                2802 non-null   int64
 22  AST                2802 non-null   int64
 23  STL                2802 non-null   int64
 24  BLK                2802 non-null   int64
 25  TOV                2802 non-null   int64
 26  PF                 2802 non-null   int64
 27  PLUS_MINUS         2802 non-null   float64
 28  HOME_TEAM          2802 non-null   bool
dtypes: bool(1), datetime64[us](1), float64(4), int64(18), str(5)
memory usage: 615.8 KB

In [29]:
df_final_standard.to_csv("nba_league_games_2024-25_standard.csv", index=False)